apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-simple-app
  template:
    metadata:
      labels:
        app: my-simple-app
    spec:
      containers:
      - name: app-container
        image: ghcr.io/OddAir/gitargotest:initial-tag
        ports:
        - containerPort: 3000